name: Build
on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable
          
      # Remove the problematic upload-artifact action entirely
      # Instead, let's use a simpler approach to list the output files
      - name: List output files
        run: |
          echo "Build completed. Output files:"
          ls -la bin/
          echo "APK should be available in the bin directory"
